defaults: &defaults
  validations:
    name:
      "validation": "required length"
      "validation-length": "min4"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Name" %>
      "validation-error-msg-length": <%= I18n.t "errors.name_length" %>
    email:
      "validation": "required email"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Email" %>
      "validation-error-msg-email": <%= I18n.t "errors.email_invalidate" %>
    phone_number:
      "validation": "required"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Phone number" %>
    password:
      "validation": "required length"
      "validation-length": "min8"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Password" %>
      "validation-error-msg-password": <%= I18n.t "errors.password" %>
    confirm_password:
      "validation": "confirmation"
      "validation-confirm": "user[password]"
      "validation-error-msg-confirmation": <%= I18n.t "errors.confirm_password" %>
    blank:
      "validation": "required"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Name" %>
    retail_sale_price:
      "validation": "number"
      "validation-allowing": "float"
      "validation-error-msg-number": <%= I18n.t "errors.number", data: "Retail sale price" %>
    discount:
      "validation": "number"
      "validation-allowing": "float"
      "validation-optional": "true"
      "validation-error-msg-number": <%= I18n.t "errors.number", data: "Discount" %>
    code:
      "validation": "required"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Code" %>
    title:
      "validation": "required"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Title" %>
    address:
      "validation": "required"
      "validation-error-msg-required": <%= I18n.t "errors.required", data: "Address" %>
  paginate:
    per_page: 15
    related_product: 6
    other_promotion: 6
    hot_product: 10
    per_page_10: 10
  image:
    size60: 60
    size150: 150
    size100: 100
    size500: 500
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
